//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileTbl
    {
        public int id { get; set; }
        public string fileName { get; set; }
        public string fileSize { get; set; }
        public string fileExtention { get; set; }
        public Nullable<System.DateTime> fileAddDate { get; set; }
        public string fileLocation { get; set; }
        public Nullable<int> fileCategoryId { get; set; }
    
        public virtual FileCategoryTbl FileCategoryTbl { get; set; }
    }
}
